version: '3'
services:
  ####################
  # React
  ####################
  react:
    image         : node:carbon
    container_name: Node
    build         : ./react-demo
    ports:
      - "3000:3000"
  #####################
  # NGINX
  #####################
  nginx:
    image         : nginx:stable
    container_name: Nginx
    build         : ./nginx
    links         :
      - react
    ports:
      - "80:80"
      - "443:443"